In [1]:
import requests
from bs4 import BeautifulSoup as bs
import pandas as pd
import numpy as np
import codecs
import time
import re
import os
from IPython.display import display, HTML
from difflib import SequenceMatcher

In [124]:
Inputline = "saH eva vAswavikaH sanyAsI mahAwmA rARtranewA vA yaH nirXanAn sevawe Bajawe vA"

In [125]:
with open("workdata/lines_submit/all_lines.txt",encoding = 'utf-8' ,mode ='r') as fr:
    lines = fr.readlines()
    
    for line in lines:
        if(line.startswith("filename : ")) :
            line1 = line
            continue
        if(line.startswith("lineno : ")) :
            line2 = line
            continue
        if(line.startswith("line : ")) :
            line3 = line
            line4 = line[7:-1]
            if(line4==Inputline) :
                break
with open("workdata/lines_submit/all_uniquelines.txt",encoding = 'utf-8' ,mode ='r') as fr:
    lines = fr.readlines()
    c = 1
    x=0
    for line in lines:
        c = c+1
       
        if(line.startswith("filename : ")) :
            if(line1 == line ) :
                x=1
            continue
        if(line.startswith("lineno : ")) :
            if(line2 == line ) :
                break
            continue
count = int(c/3)

fnames1 = os.listdir("workdata/lines_submit/correct_lines/sorteddata/")
fnames2 = os.listdir("workdata/lines_submit/wrong_lines/sorteddata/")
name = str(count)
if name in fnames1[0:] :
    path = "workdata/lines_submit/correct_lines/sorteddata/"
elif name in fnames2[0:]:
    path = "workdata/lines_submit/wrong_lines/sorteddata/"

In [126]:
fname1 = path+name+"/dataframe.txt"
fname2 = path+name+"/input_line.txt"
fname3 = path+name+"/original_line.txt"
fname5 = path+name+"/dataframe_withsandhi.txt"
fname6 = path+name+"/conflicts.csv"
fname7 = path+name+"/problem_words.txt"

In [127]:
with open(fname3,encoding = 'utf-8' ,mode ='r') as fr :
    for line in fr.readlines() :
        print(line)
with open(fname2,encoding = 'utf-8' ,mode ='r') as fr :
    for line in fr.readlines() :
        print(line)

filename : 9std_sents_GOLD_complex.txt

lineno : 456

SENT: saH eva vAswavikaH sanyAsI mahAwmA rARtranewA vA yaH nirXanAn sevawe Bajawe vA

ANALYSIS:

1	saH	SSN

2	eva	INTF	sambanXaH,1

3	vAswavikaH	NV	viSeRaNam,7

4	sanyAsI	NP	samucciwam,7

5	mahAwmA	NP	samucciwam,7

6	rARtranewA		samucciwam,7

7	vA	AVK	viSeRaNam,1

8	yaH	SN

9	nirXanAn		karma,12

10	sevawe	KP	anyawaraH,12

11	Bajawe	KP	anyawaraH,12

12	vA	AVK	prawiyogI,1

input line : saH eva vAswavikaH sanyAsI mahAwmA rARtranewA vA yaH nirXanAn sevawe Bajawe vA

converted line : saḥ eva vāstavikaḥ sanyāsī mahātmā_rāṣṭranetā_vā_yaḥ nirdhanān sevate bhajate vā

converted line char :s,a,ḥ, ,e,v,a, ,v,ā,s,t,a,v,i,k,a,ḥ, ,s,a,n,y,ā,s,ī, ,m,a,h,ā,t,m,ā,_,r,ā,ṣ,ṭ,r,a,n,e,t,ā,_,v,ā,_,y,a,ḥ, ,n,i,r,dh,a,n,ā,n, ,s,e,v,a,t,e, ,bh,a,j,a,t,e, ,v,ā,

In [122]:
df = pd.read_csv(fname5,encoding = 'utf-8' ,sep = ',')
df

,id,level,color_class,position,chunk_no,word,lemma,pre_verb,morph,colspan,wordlenth,aux_inf,word_slp1,sandhi_indexs,sandhi_words
0,0,1,mauve_back,0,1,tataḥ,tad,NaN,tasil,5,5,NaN,tataH,NaN,NaN
1,1,1,light_blue_back,6,2,te,tad,NaN,acc. du. n.,2,2,NaN,te,NaN,NaN
2,2,1,light_blue_back,6,2,te,tad,NaN,nom. du. n.,2,2,NaN,te,NaN,NaN
3,3,1,light_blue_back,6,2,te,tad,NaN,nom. pl. m.,2,2,NaN,te,NaN,NaN
4,4,1,light_blue_back,6,2,te,tad,NaN,acc. du. f.,2,2,NaN,te,NaN,NaN
5,5,1,light_blue_back,6,2,te,tad,NaN,nom. du. f.,2,2,NaN,te,NaN,NaN
6,6,1,light_blue_back,6,2,te,yuṣmad,NaN,g. sg. *,2,2,NaN,te,NaN,NaN
7,7,1,light_blue_back,6,2,te,yuṣmad,NaN,dat. sg. *,2,2,NaN,te,NaN,NaN
8,8,1,deep_sky_back,9,3,sarve,sarva,NaN,nom. pl. m.,5,5,NaN,sarve,NaN,NaN
9,9,1,deep_sky_back,9,3,sarve,sarva,NaN,loc. sg. m.,5,5,NaN,sarve,NaN,NaN
10,10,1,deep_sky_back,9,3,sarve,sarva,NaN,acc. du. n.,5,5,NaN,sarve,NaN,NaN
11,11,1,deep_sky_back,9,3,sarve,sarva,NaN,nom. du. n.,5,5,NaN,sarve,NaN,NaN
12,12,1,deep_sky_back,9,3,sarve,sarva,NaN,loc. sg. n.,5,5,NaN,sarve,NaN,NaN
13,13,1,yellow_back,15,4,guñja,guñja,NaN,iic.,5,5,NaN,guYja,"40, 41,","aphalam(aPalam), a(a),"
14,14,1,deep_sky_back,20,4,phalam,phala,NaN,acc. sg. n.,5,6,NaN,Palam,NaN,NaN
15,15,1,deep_sky_back,20,4,phalam,phala,NaN,nom. sg. n.,5,6,NaN,Palam,NaN,NaN
16,16,1,mauve_back,26,5,paritaḥ,pari,NaN,tasil,7,7,NaN,paritaH,NaN,NaN
17,17,1,carmin_back,34,6,upaviśanti,viś,upa,pr. [6] ac. pl. 3,10,10,sence of lemma = 1,upaviSanti,NaN,NaN
18,18,2,deep_sky_back,0,1,tataḥ,tata,NaN,nom. sg. m.,5,5,sence of lemma = 2,tataH,NaN,NaN
19,19,2,light_blue_back,9,3,sarve,sarva,NaN,acc. du. f.,5,5,NaN,sarve,NaN,NaN
20,20,2,light_blue_back,9,3,sarve,sarva,NaN,nom. du. f.,5,5,NaN,sarve,NaN,NaN
21,21,2,deep_sky_back,15,4,guñjā,guñja,NaN,nom. sg. f.,5,5,NaN,guYjA,"40, 41,","aphalam(aPalam), a(a),"
22,22,2,deep_sky_back,34,6,upaviśanti,viśat,upa,acc. pl. n.,10,10,{ ppr. [6] ac. }[upa-viś_1],upaviSanti,NaN,NaN
23,23,2,deep_sky_back,34,6,upaviśanti,viśat,upa,nom. pl. n.,10,10,{ ppr. [6] ac. }[upa-viś_1],upaviSanti,NaN,NaN
24,24,3,light_blue_back,0,1,tataḥ,tad,NaN,abl. pl. n.,5,5,NaN,tataH,NaN,NaN
25,25,3,light_blue_back,0,1,tataḥ,tad,NaN,abl. du. n.,5,5,NaN,tataH,NaN,NaN
26,26,3,light_blue_back,0,1,tataḥ,tad,NaN,abl. sg. n.,5,5,NaN,tataH,NaN,NaN
27,27,3,light_blue_back,0,1,tataḥ,tad,NaN,abl. pl. m.,5,5,NaN,tataH,NaN,NaN
28,28,3,light_blue_back,0,1,tataḥ,tad,NaN,abl. du. m.,5,5,NaN,tataH,NaN,NaN
29,29,3,light_blue_back,0,1,tataḥ,tad,NaN,abl. sg. m.,5,5,NaN,tataH,NaN,NaN
30,30,3,light_blue_back,0,1,tataḥ,tad,NaN,abl. pl. f.,5,5,NaN,tataH,NaN,NaN
31,31,3,light_blue_back,0,1,tataḥ,tad,NaN,abl. du. f.,5,5,NaN,tataH,NaN,NaN
32,32,3,light_blue_back,0,1,tataḥ,tad,NaN,abl. sg. f.,5,5,NaN,tataH,NaN,NaN
33,33,3,lawngreen_back,9,3,sarve,sarva,NaN,voc. du. n.,5,5,NaN,sarve,NaN,NaN
34,34,3,lawngreen_back,9,3,sarve,sarva,NaN,voc. du. f.,5,5,NaN,sarve,NaN,NaN
35,35,3,lawngreen_back,9,3,sarve,sarva,NaN,voc. sg. f.,5,5,NaN,sarve,NaN,NaN
36,36,3,carmin_back,15,4,guñja,guñj,NaN,imp. [1] ac. sg. 2,5,5,NaN,guYja,"40, 41,","aphalam(aPalam), a(a),"
37,37,3,lawngreen_back,34,6,upaviśanti,viśat,upa,voc. sg. f.,10,10,{ ppr. [6] ac. }[upa-viś_1],upaviSanti,NaN,NaN
38,38,3,lawngreen_back,34,6,upaviśanti,viśat,upa,voc. pl. n.,10,10,{ ppr. [6] ac. }[upa-viś_1],upaviSanti,NaN,NaN
39,39,4,deep_sky_back,0,1,tataḥ,tata,NaN,nom. sg. m.,5,5,{ pp. }[tan_1] sence of lemma = 1,tataH,NaN,NaN
40,40,4,carmin_back,19,4,aphalam,phal,NaN,impft. [1] ac. sg. 1,6,7,NaN,aPalam,NaN,NaN
41,41,5,yellow_back,19,4,a,a,NaN,iic.,1,1,NaN,a,NaN,NaN

In [123]:
cf = pd.read_csv(fname6,encoding = 'utf-8' ,sep = ',')
cf

    0  1  2  3  4  5  6  7  8  9 ...  32  33  34  35  36  37  38  39  40  41
0   0  0  0  0  0  0  0  0  0  0 ...   2   0   0   0   0   0   0   2   0   0
1   0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
2   0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
3   0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
4   0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
5   0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
6   0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
7   0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
8   0  0  0  0  0  0  0  0  0  0 ...   0   2   2   2   0   0   0   0   0   0
9   0  0  0  0  0  0  0  0  0  0 ...   0   2   2   2   0   0   0   0   0   0
10  0  0  0  0  0  0  0  0  0  0 ...   0   2   2   2   0   0   0   0   0   0
11  0  0  0  0  0  0  0  0  0  0 ...   0   2   2   2   0   0   0   0   0   0
12  0  0  0  0  0  0  0  0  0  0 ...   0   2   2   2   0   0   0   0   0   0
13  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   2   0   0   0   1   1
14  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   2   0
15  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   2   0
16  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
17  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   2   2   0   0   0
18  2  0  0  0  0  0  0  0  0  0 ...   2   0   0   0   0   0   0   2   0   0
19  0  0  0  0  0  0  0  0  2  2 ...   0   2   2   2   0   0   0   0   0   0
20  0  0  0  0  0  0  0  0  2  2 ...   0   2   2   2   0   0   0   0   0   0
21  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   2   0   0   0   1   1
22  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   2   2   0   0   0
23  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   2   2   0   0   0
24  2  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   2   0   0
25  2  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   2   0   0
26  2  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   2   0   0
27  2  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   2   0   0
28  2  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   2   0   0
29  2  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   2   0   0
30  2  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   2   0   0
31  2  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   2   0   0
32  2  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   2   0   0
33  0  0  0  0  0  0  0  0  2  2 ...   0   0   0   0   0   0   0   0   0   0
34  0  0  0  0  0  0  0  0  2  2 ...   0   0   0   0   0   0   0   0   0   0
35  0  0  0  0  0  0  0  0  2  2 ...   0   0   0   0   0   0   0   0   0   0
36  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   1   1
37  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
38  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
39  2  0  0  0  0  0  0  0  0  0 ...   2   0   0   0   0   0   0   0   0   0
40  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   1   0   0   0   0   2
41  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   1   0   0   0   2   0

[42 rows x 42 columns]

In [128]:
with open("workdata/lines_submit/analasys/undifined_words.txt",encoding = 'utf-8' ,mode ='r') as fr :
    pbwords = fr.readlines()
cf = pd.read_csv("workdata/lines_submit/analasys/undifined_wordsfreaquency.csv",encoding = 'utf-8' ,sep = ',')
cd = cf.T
cd.loc[cd[0] >5]

               0
tathā_eva     21
bhagavan      11
tasya_eva      7
sudūre         6
sadā_eva      10
atra_eva       8
tadā_aham      9
prārthitavān  10

               0
tathā_eva     21
bhagavan      11
tasya_eva      7
sudūre         6
sadā_eva      10
atra_eva       8
tadā_aham      9
prārthitavān  10

In [ ]:
input